---
title: > 
  `\vspace{-1.5cm}`{=latex} STAT 441 Project Statement of Contributions
author: "Maisha Thasin, Joseph Wang (Group 25, undergraduate)"
date: "Winter 2023"
output: 
  pdf_document:
    md_extensions: +hard_line_breaks
geometry: margin=1.5cm
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Statement of Contributions
Both Maisha and Joseph searched for and selected the dataset. Both members contributed to the initial investigation and dataset preprocessing, and participated in shaping the research question. Maisha performed the exploratory data analysis and future research ideas. Joseph performed the dataset analysis and discussion of existing analyses.

Maisha trained the Support Vector Machine, Logistic Regression, and K-Nearest Neighbour classifiers, and contributed those sections to the report. Joseph trained the Decision Tree, Random Forest, and Neural Network classifiers, and contributed those sections to the report. Both members contributed figures and tables to the report, and both members made significant revisions and additions to the report.